# version: '3.8'

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: alexei
      POSTGRES_DB: order_service
    ports:
      - "3101:3101"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: .
    ports:
      - "3100:3100"  # Node.js слушает 3100 порт
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: alexei
      DB_NAME: order_service
    depends_on:
      - db

volumes:
  postgres_data: